falcon:
  url: https://github.com/socketry/falcon
  command: bundle exec bake test
puma:
  url: https://github.com/puma/puma
  command: bundle exec rake compile; test/runner -v test_puma_localhost_authority.rb
